name: Deploy Angular to Hostinger (FTP)

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular project
        run: npm run build -- --configuration=production

      - name: Verify build output
        run: ls -la ./dist/ecommerce-website/browser/

      # Step to Delete Old Files Except .htaccess
      - name: Clean up old files on server (excluding .htaccess)
        run: |
          sudo apt-get install -y lftp
          lftp -d -u "${{ secrets.FTPUSERNAME }}","${{ secrets.FTPPASSWORD }}" ${{ secrets.FTPHOST }} <<EOF
          set ftp:ssl-allow no
          cd /public_html/qa-store/
          glob -a rm -rf [!.]*    # Deletes everything except .htaccess
          bye
          EOF
        shell: bash

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTPHOST }}
          username: ${{ secrets.FTPUSERNAME }}
          password: ${{ secrets.FTPPASSWORD }}
          local-dir: ./dist/ecommerce-website/browser/
          server-dir: /public_html/qa-store/
          exclude: |
            **/.htaccess
